---

app:
  bot.token: {{ bot_token }}
  polling.timeout.seconds: {{ polling_timeout_seconds }}
  network.failure.pause.minutes: {{ network_failure_pause_minutes }}
  request.failure.threshold: {{ request_failure_threshold }}
