---

app:

  bot.token: {{ bot_token }}

  polling.timeout.seconds: 10
  network.failure.pause.minutes: 5
  request.failure.threshold: 3

  rates.refresh.cron: 0 0 * * * *

  subscription.cron: 0 0 7 * * *
  subscription.zone: Europe/Moscow

  redis.host: localhost
  redis.port: 6379
  redis.db.index: 0