---

- hosts: server

  tasks:

    - name: include variables from external file
      include_vars: variables.yml

    - name: remove previous setup
      file: path={{ remote_path }} state=absent

    - name: create root directory
      file: path={{ remote_path }} state=directory

    - name: copy scripts
      copy:
        src: ../bin
        dest: "{{ remote_path }}"

    - name: copy application
      copy:
        src: ../../build/libs/simple-telegram-bot.jar
        dest: "{{ remote_path }}/bin/simple-telegram-bot.jar"

    - name: create configuration directory
      file:
        path: "{{ remote_path }}/config"
        state: directory

    - name: copy logging configuration
      copy:
        src: ../config/logback.xml
        dest: "{{ remote_path }}/config/logback.xml"

    - name: combine and copy application configuration
      template:
        src: ../config/application.yml
        dest: "{{ remote_path }}/config/application.yml"

    - name: make start and shutdown scripts executable
      file:
        path: "{{ remote_path }}/bin/{{ item }}"
        mode: 0544
      with_items:
        - start.sh
        - stop.sh

    - name: start application
      shell: ./start.sh
      args:
        chdir: "{{ remote_path }}/bin/"
      environment:
        JAVA_HOME: "{{ java_home }}"