---

- hosts: server

  tasks:

    - name: include variables from external file
      include_vars: variables.yml

    - name: stop application
      script: ../bin/stop.sh

    - name: ensure root directory exists
      file: path={{ remote_path }} state=directory

    - name: install java
      script: install_java.sh {{ remote_path }}

    - name: install redis
      script: install_redis.sh {{ remote_path }}

    - name: remove 'bin' directory from previous setup
      file: path="{{ remote_path }}/bin" state=absent

    - name: remove 'config' directory from previous setup
      file: path="{{ remote_path }}/config" state=absent

    - name: remove 'logs' directory from previous setup
      file: path="{{ remote_path }}/logs" state=absent

    - name: copy scripts
      copy:
        src: ../bin
        dest: "{{ remote_path }}"

    - name: copy application
      copy:
        src: ../../build/libs/simple-telegram-bot.jar
        dest: "{{ remote_path }}/bin/simple-telegram-bot.jar"

    - name: create configuration directory
      file: path="{{ remote_path }}/config" state=directory

    - name: create redis data directory
      file: path="{{ remote_path }}/redis-data" state=directory

    - name: copy logging configuration
      copy:
        src: ../config/logback.xml
        dest: "{{ remote_path }}/config/logback.xml"

    - name: resolve and copy application configuration
      template:
        src: ../config/application.yml
        dest: "{{ remote_path }}/config/application.yml"

    - name: resolve and copy redis configuration
      template:
        src: ../config/redis.conf
        dest: "{{ remote_path }}/config/redis.conf"

    - name: restart redis
      script: restart_redis.sh {{ remote_path }}

    - name: make start and shutdown scripts executable
      file:
        path: "{{ remote_path }}/bin/{{ item }}"
        mode: 0544
      with_items:
        - start.sh
        - stop.sh

    - name: start application
      shell: ./start.sh > start.log
      args:
        chdir: "{{ remote_path }}/bin/"
      environment:
        JAVA_HOME: "{{ remote_path }}/java"